#!/bin/sh
#
#  Installs Sway WM configuration into my $XDG_CONFIG_HOME.
#
#  Systemd user Services used:
#    kanshi - Wayland daemon that automatically configures outputs
#    mako - Notification daemon for Wayland
#    mpd - Music daemon for linux
#

export scriptName=swayInstall

XDG_CONFIG_HOME="${XDG_CONFIG_HOME:=$HOME/.config}"
SWAY_GIT_REPO="${SWAY_GIT_REPO:=$HOME/devel/sway-env}"
umask 0022

cd "$SWAY_GIT_REPO" || {
   printf "\\nError: Failed to cd into '%s'\\n" "$SWAY_GIT_REPO"
   return 1
}

## Source install infrastructure if necessary
. ./installSource.sh

## Files to install

CONFIG_FILES='
   alacritty/alacritty_arch.yml
   alacritty/alacritty.yml
   kanshi/config
   mako/config
   mpd/mpd.conf
   sway/config
   sway/config_bg_color
   sway/config_bg_picture
   waybar/config
   waybar/style.css
   wofi/config
   wofi/style.css
'

SYSTEMD_SERVICE_FILES='
   systemd/user/kanshi.service
   systemd/user/mako.service
   systemd/user/sway-session.target
'

RM_TARGET_ITEMS="
   $HOME/.mako
   $HOME/.sway
"

DIRS_TO_CREATE="
   $XDG_CONFIG_HOME/mpd/playlists
"

## Install or Check

# Install Sway and other Sway related config files
for file in $CONFIG_FILES $SYSTEMD_SERVICE_FILES
do
   install_file "$XDG_CONFIG_HOME" "$file" ./config 0644 "$switch"
done
chmod 0755 "$XDG_CONFIG_HOME"

# Remove/report no longer needed files and directories
for item in $RM_TARGET_ITEMS
do
   remove_item "$item" target
done

# Create or report on missing directories
for DIR in $DIRS_TO_CREATE
do
   ensure_dir "$DIR"
done

# Final adjustments/tweaks/tasks
case "$switch" in
   install)
      # The background picture I personally use is from
      # 'https://www.facebook.com/alittleofmeinyou/photos/325964185818238'
      picture="$HOME"/Pictures/Desktops/SwayBG.jpg
      bg_link="$XDG_CONFIG_HOME"/sway/config_bg
      if test -f "$picture"
      then
         bg="$XDG_CONFIG_HOME"/sway/config_bg_picture
      else
         bg="$XDG_CONFIG_HOME"/sway/config_bg_color
      fi
      test -L "$bg_link" && rm "$bg_link"
      ln -s "$bg" "$bg_link"

      # Reload Systemd user services in case config files get updated
      systemctl --user daemon-reload
      :
      ;;
   repo)
      # Get git status info on repo
      printf '\nGit Status:\n'
      git status -s
      ;;
   target)
      :
      ;;
esac
